# Generated by Django 4.1.3 on 2023-05-18 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='imagen',
            field=models.ImageField(blank=True, default='descarga.png', null=True, upload_to=''),
        ),
    ]
