# Generated by Django 4.1.3 on 2023-05-18 09:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='logros',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, size=None),
        ),
    ]
