# Generated by Django 4.1.3 on 2023-05-23 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_solicitudenviada_profile_solicitudrecivida'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='solicitudRecivida',
            new_name='solicitudRecibida',
        ),
    ]
