# Generated by Django 4.1.3 on 2023-05-24 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_ubicacion_parquecalistenia_placeid'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_th',
            field=models.BooleanField(default=False),
        ),
    ]
