# Generated by Django 4.1.3 on 2023-05-27 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_useraccount_is_th'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='logros',
        ),
        migrations.AddField(
            model_name='profile',
            name='logros',
            field=models.ManyToManyField(blank=True, related_name='usuarios_con_logro', to='accounts.logro'),
        ),
    ]
