# Generated by Django 4.1.3 on 2023-05-28 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_material_parquecalistenia_materiales'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='nombre',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
