# Generated by Django 4.1.3 on 2023-05-29 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_profile_mismegustan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='misMeGustan',
        ),
    ]
