# Generated by Django 4.1.3 on 2023-05-29 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_remove_profile_mismegustan'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='misMeGustan',
            field=models.ManyToManyField(blank=True, related_name='mis_mg', to='accounts.publicacion'),
        ),
    ]
