# Generated by Django 4.1.3 on 2023-06-01 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_profile_mismegustan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parquecalistenia',
            name='materiales',
        ),
        migrations.DeleteModel(
            name='Material',
        ),
    ]
