# Generated by Django 4.1.3 on 2023-06-03 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_material_reserva_materiales'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='is_th',
            new_name='is_private',
        ),
        migrations.AddField(
            model_name='profile',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
