# Generated by Django 4.1.3 on 2023-06-05 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_remove_useraccount_is_private_profile_is_private'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parquecalistenia',
            name='imagen',
        ),
        migrations.AddField(
            model_name='parquecalistenia',
            name='imagenUrl',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
