# Generated by Django 4.1.3 on 2023-06-05 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_remove_parquecalistenia_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parquecalistenia',
            name='imagenUrl',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
