# Generated by Django 4.1.3 on 2023-06-05 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alter_parquecalistenia_imagenurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='logros',
        ),
        migrations.AddField(
            model_name='parquecalistenia',
            name='baneado',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Logro',
        ),
    ]
