# Generated by Django 4.1.3 on 2023-06-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_remove_profile_logros_parquecalistenia_baneado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parquecalistenia',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parquecalistenia',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
