# Generated by Django 4.1.3 on 2023-06-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_parquecalistenia_dislikes_parquecalistenia_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parquecalistenia',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='parquecalistenia',
            name='likes',
        ),
        migrations.AddField(
            model_name='parquecalistenia',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='parques_dislikes', to='accounts.profile'),
        ),
        migrations.AddField(
            model_name='parquecalistenia',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='parques_likes', to='accounts.profile'),
        ),
    ]
