# Generated by Django 4.1.3 on 2023-06-05 11:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_remove_parquecalistenia_dislikes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parquecalistenia',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='parques_dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='parquecalistenia',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='parques_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
