# Generated by Django 4.1.3 on 2023-06-06 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_alter_parquecalistenia_dislikes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='imagen',
            field=models.TextField(blank=True, null=True),
        ),
    ]
