# Generated by Django 4.1.3 on 2023-06-08 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_alter_publicacion_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='parques_calistenia',
        ),
    ]
