# Generated by Django 4.1.3 on 2023-06-12 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_rutina_profile_experiencia_profile_nivel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rutina',
            old_name='experiencia',
            new_name='repeticiones_set',
        ),
        migrations.RemoveField(
            model_name='rutina',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='rutina',
            name='nombre',
        ),
        migrations.AlterField(
            model_name='rutina',
            name='nivel',
            field=models.IntegerField(choices=[(1, 'Principiante'), (2, 'Intermedio'), (3, 'Avanzado')]),
        ),
        migrations.CreateModel(
            name='SetEjercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repeticiones', models.IntegerField()),
                ('ejercicio', models.CharField(max_length=255)),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.rutina')),
            ],
        ),
    ]
