# Generated by Django 4.1.3 on 2023-06-12 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_alter_setejercicio_rutina'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutina',
            name='nombre',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
