# Generated by Django 4.1.3 on 2023-06-13 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_rutina_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutina',
            name='perfiles_abandonados',
            field=models.ManyToManyField(blank=True, related_name='rutinas_abandonadas', to='accounts.profile'),
        ),
        migrations.AddField(
            model_name='rutina',
            name='perfiles_completados',
            field=models.ManyToManyField(blank=True, related_name='rutinas_completadas', to='accounts.profile'),
        ),
    ]
