version: '3'

services:
  web:
    build:
      context: .docker/frontend/
    container_name: tfg_frontend
    user: node
    ports:
      - "5173:5173"
    volumes:
      - ./fronted:/home/node

  server:
    build:
      context: .docker/server/
    container_name: tfg_server
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - database

  database:
    image: postgres:14.7
    container_name: tfg_database
    volumes:
      - '.docker/database/data:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: ${DB_NAME:-auth_system}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-2203}
