version: '3'

services:
  frontend:
    build:
      context: .docker/frontend/
    container_name: tfg_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./fronted:/home/node

  backend:
    build:
      context: .docker/backend/
    container_name: tfg_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/usr/src/app
    environment:
      DB_HOST: ${DB_HOST}
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres:14.7
    container_name: tfg_database
    volumes:
      - '.docker/database/data:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: ${DB_NAME:-auth_system}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-2203}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
